[theme]
primaryColor = "#60a5fa"        # blue-400
backgroundColor = "#0e1117"      # near-black
secondaryBackgroundColor = "#161a23" # dark slate
textColor = "#e5e7eb"           # gray-200
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
